name: Deploy S3ToS3 Lambda Function

on:
  push:
    branches:
      - main 
      - dev
    paths:
      - 'lambda/s3tos3/**' # Trigger only when changes occur in specific Lambda function folder

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r lambda/requirements.txt -t src/s3tos3/package

      - name: Zip Lambda deployment package
        run: |
          cd src/s3tos3
          zip -r ../../lambda_package.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Your AWS region

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name s3tos3-lambda-function \
            --zip-file fileb://lambda_package.zip

